-- MySQL Script generated by MySQL Workbench
-- Tue Dec  5 14:58:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema python_game_data
-- -----------------------------------------------------
-- Drop the database if it exists
DROP DATABASE IF EXISTS `python_game_data`;

-- -----------------------------------------------------
-- Schema python_game_data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `python_game_data` DEFAULT CHARACTER SET utf8 ;
USE `python_game_data` ;

-- -----------------------------------------------------
-- Table `python_game_data`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `python_game_data`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nickname` VARCHAR(25) NOT NULL,
  `Password` VARCHAR(255) NOT NULL, -- Adjust the length as needed
  `UserLevel` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `idx_Pseudo` (`Nickname` ASC) VISIBLE,
  INDEX `idx_UserLevel` (`UserLevel` ASC) VISIBLE);

-- -----------------------------------------------------
-- Table `python_game_data`.`Exercices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `python_game_data`.`Exercices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `python_game_data`.`Results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `python_game_data`.`Results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Date_Hours` DATETIME NOT NULL,
  `Duration` TIME NOT NULL,
  `Number_of_try` INT NOT NULL,
  `Number_of_Sucess` INT NOT NULL,
  `fk_users_id` INT NOT NULL,
  `fk_exercice_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Resultat_Utilisateur1_idx` (`fk_users_id` ASC) VISIBLE,
  INDEX `fk_Resultat_Exercice1_idx` (`fk_exercice_id` ASC) VISIBLE,
  CONSTRAINT `fk_Resultat_Utilisateur1`
    FOREIGN KEY (`fk_users_id`)
    REFERENCES `python_game_data`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultat_Exercice1`
    FOREIGN KEY (`fk_exercice_id`)
    REFERENCES `python_game_data`.`Exercices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- Réinitialiser les droits à la fin du script
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
